// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20221209113148_InitMigartion")]
    partial class InitMigartion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginnigTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginnigTime = new DateTime(2022, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "Varicose veins",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeginnigTime = new DateTime(2022, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "Polyarteritis nodosa",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 3,
                            BeginnigTime = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "Prevotella infection",
                            PatientId = 3
                        },
                        new
                        {
                            Id = 4,
                            BeginnigTime = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "Cytomegalovirus infection",
                            PatientId = 4
                        },
                        new
                        {
                            Id = 5,
                            BeginnigTime = new DateTime(2022, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "Tungiasis",
                            PatientId = 5
                        },
                        new
                        {
                            Id = 6,
                            BeginnigTime = new DateTime(2022, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "Hypotonia",
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2002, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Zach Curtis"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1996, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Max Thomson"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2003, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Eva Reyes"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2000, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Farhan Greene"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1978, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lorna Carpenter"
                        });
                });

            modelBuilder.Entity("Model.Disease", b =>
                {
                    b.HasOne("Model.Patient", "Patient")
                        .WithMany("MedicalHistory")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Model.Patient", b =>
                {
                    b.Navigation("MedicalHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
